# Generated by Django 3.2.9 on 2021-12-29 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=1023, null=True)),
                ('date', models.DateField()),
                ('frequency', models.DurationField(null=True)),
                ('value', models.BigIntegerField()),
                ('is_confirmed', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_order_number', models.PositiveIntegerField()),
                ('execution_date', models.DateField()),
                ('value', models.PositiveBigIntegerField()),
                ('is_confirmed', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactionstorage')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=63)),
                ('description', models.TextField(max_length=1023)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('value', models.PositiveBigIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
